# SPECIAL HW - ONLINE STUDENTS

### HW 9: L11 - p2

The code also checks if the matrix is a square matrix and if it is invertible (i.e., its determinant is not equal to zero). If these conditions are not met, it will inform you that the inverse cannot be computed.

In [1]:
import numpy as np

A_matrix = [
    [1, 1, 1, 0],
    [1, 0, 0, 0],
    [0, 0, 1, 1],
    [0, 3, 1, 0],
]

def compute_inverse(matrix):
    # Check if the matrix is square
    rows = len(matrix)
    cols = len(matrix[0])

    if rows != cols:
        print("The matrix is not square, so the inverse cannot be computed.")
        return None

    # Convert the matrix to a NumPy array
    matrix_np = np.array(matrix)

    # Check if the matrix is invertible
    det = np.linalg.det(matrix_np)
    if det == 0:
        print("The matrix is not invertible, so the inverse cannot be computed.")
        return None

    # Compute the inverse
    inverse = np.linalg.inv(matrix_np)
    return inverse

A_inverse = compute_inverse(A_matrix)
if A_inverse is not None:
    print("Inverse of A matrix:")
    print(A_inverse)


Inverse of A matrix:
[[ 1.11022302e-16  1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [-5.00000000e-01  5.00000000e-01  0.00000000e+00  5.00000000e-01]
 [ 1.50000000e+00 -1.50000000e+00  0.00000000e+00 -5.00000000e-01]
 [-1.50000000e+00  1.50000000e+00  1.00000000e+00  5.00000000e-01]]


A_inervse_matrix = [  
    [0, 1, 0, 0],  
    [-0.5, 0.5, 0, 0.5],  
    [1.5, -1.5, 0, -0.5],  
    [-1.5, 1.5, 1, 0.5],  
]

### HW10: L13 - p3

Solve the next optimization problem: 

min x1 + x2 + x3 + x4 + x5

A matrix = 
3, 2, 1, 0, 0
5, 1, 1, 1, 0
2, 5, 1, 0, 1

b_ matrix = 
1
3
4

Using the Hungarian method with the SciPy library as for the project: 

min (x1 + x2 + x3 + x4 + x5)   
A * x >= b

In [2]:
from scipy.optimize import linprog

# Objective function coefficients
c = [1, 1, 1, 1, 1]

# Inequality constraint matrix and vector
A = [
    [-3, -2, -1,  0,  0],
    [-5, -1, -1, -1,  0],
    [-2, -5, -1,  0, -1],
]
b = [-1, -3, -4]

# Boundaries for variables (x1, x2, x3, x4, x5) - assuming non-negative variables
bounds = [(0, None) for _ in range(len(c))]

# Solving the linear programming problem
result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method="highs")

print("Optimal solution:")
print(result.x)
print("Minimum value of the objective function:")
print(result.fun)


max (x1 + x2 + x3 + x4 + x5)   
A * x <= b

In [ ]:
from scipy.optimize import linprog

# Objective function coefficients (negated for maximization)
c = [-1, -1, -1, -1, -1]

# Inequality constraint matrix and vector
A = [
    [3, 2, 1, 0, 0],
    [5, 1, 1, 1, 0],
    [2, 5, 1, 0, 1],
]
b = [1, 3, 4]

# Boundaries for variables (x1, x2, x3, x4, x5) - assuming non-negative variables
bounds = [(0, None) for _ in range(len(c))]

# Solving the linear programming problem
result = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method="highs")

print("Optimal solution:")
print(result.x)
print("Maximum value of the objective function:")
print(-result.fun)  # Negate the result to obtain the maximum value


Optimal solution:
[0. 0. 0. 3. 4.]
Maximum value of the objective function:
7.0


### HW11: L14 - p2

Given the current basis matrix B and cost vector c, let's find the basic feasible solution, calculate the reduced costs, and update the basis using the simplex algorithm.

The current basis matrix B and the basic variables are:

$$
B = \begin{bmatrix} 1 & 0 & 0 \\ 1 & 1 & 0 \\ 1 & 0 & 1 \end{bmatrix} \quad \text{with basic variables: } x_1, x_4, x_5
$$

To find the basic feasible solution, solve B * x_B = b:

$$
x_B = B^{-1} * b = \begin{bmatrix} 1 & 0 & 0 \\ -1 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} * \begin{bmatrix} 1 \\ 3 \\ 4 \end{bmatrix}
$$

$$
x_B = \begin{bmatrix} 1 \\ 2 \\ 4 \end{bmatrix}
$$

So, the basic feasible solution is x1 = 1, x4 = 2, x5 = 4, and the non-basic variables are x2 = x3 = 0.

Now let's find the reduced costs by calculating c - c_B * A:

$$
c_B = [1, 1, 1] \\
A = \begin{bmatrix} 3 & 2 & 1 & 0 & 0 \\ 5 & 1 & 1 & 1 & 0 \\ 2 & 5 & 1 & 0 & 1 \end{bmatrix} \\
c - c_B * A = [1, 1, 1, 1, 1] - [1, 1, 1] * A
$$

$$
c - c_B * A = [0, -2, 0, 0, 0]
$$

The reduced cost for x2 is -2, which is negative, indicating that we can improve the objective function by introducing x2 into the basis. To find the leaving variable, we calculate the minimum ratio test:

$$
\frac{\text{RHS}}{\text{column of entering variable }(x_2)} = \begin{bmatrix} \frac{1}{2} \\ \frac{3}{1} \\ \frac{4}{5} \end{bmatrix}
$$

Minimum ratio = 1/2

Since 1/2 is the smallest ratio, x1 will leave the basis, and x2 will enter. The new basis matrix B' and cost vector c' are:

$$
B' = \begin{bmatrix} 2 & 0 & 0 \\ 1 & 1 & 0 \\ 5 & 0 & 1 \end{bmatrix} \quad \text{with basic variables: } x_2, x_4, x_5 \\
c' = [0, 1, 1, 1, 1]
$$




Continuing the simplex algorithm with the new basis and cost vector:

The new basis matrix B' and the basic variables are:

$$
B' = \begin{bmatrix} 2 & 0 & 0 \\ 1 & 1 & 0 \\ 5 & 0 & 1 \end{bmatrix} \quad \text{with basic variables: } x_2, x_4, x_5
$$

To find the new basic feasible solution, solve B' * x_B' = b:

$$
x_B' = B'^{-1} * b = \begin{bmatrix} 1/2 & 0 & 0 \\ -1/2 & 1 & 0 \\ -5/2 & 0 & 1 \end{bmatrix} * \begin{bmatrix} 1 \\ 3 \\ 4 \end{bmatrix}
$$

$$
x_B' = \begin{bmatrix} 1/2 \\ 5/2 \\ 2 \end{bmatrix}
$$

So, the new basic feasible solution is x2 = 1/2, x4 = 5/2, x5 = 2, and the non-basic variables are x1 = x3 = 0.

Now let's find the reduced costs by calculating c' - c_B' * A:

$$
c_B' = [0, 1, 1] \\
A = \begin{bmatrix} 3 & 2 & 1 & 0 & 0 \\ 5 & 1 & 1 & 1 & 0 \\ 2 & 5 & 1 & 0 & 1 \end{bmatrix} \\
c' - c_B' * A = [1, 0, 1, 1, 1] - [0, 1, 1] * A
$$

$$
c' - c_B' * A = [1, 0, 1, 1, 1]
$$

There are no negative reduced costs, which means we have found the optimal solution. The optimal solution is x2 = 1/2, x4 = 5/2, x5 = 2, with x1 = x3 = 0, and the minimum value of the objective function is:

$$
Z_{min} = x_1 + x_2 + x_3 + x_4 + x_5 = 0 + \frac{1}{2} + 0 + \frac{5}{2} + 2 = 5
$$


### HW12: L17&18 - 94

To illustrate how to find a flow from s to t of value f with minimum cut and transform it into a transshipment problem, I'll use an example of a flow network. Let's consider the following flow network:

Nodes: s, a, b, c, t
Edges with capacities:

s -> a: 4  
s -> b: 3  
a -> c: 3  
b -> c: 2  
b -> a: 1  
c -> t: 5  

Find a flow from s to t of value f with minimum cut:  

Using the Ford-Fulkerson algorithm or the Edmonds-Karp algorithm, we can find the maximum flow and the corresponding minimum cut.  

In this example, the maximum flow is 5, and the flow along the edges is as follows:  

s -> a: 3  
s -> b: 2  
a -> c: 3   
b -> c: 2  
b -> a: 0  
c -> t: 5  

Transform the flow problem into a transshipment problem:  

To transform the flow problem into a transshipment problem, we introduce a new commodity k, with a demand of 5 units from s to t. We then modify the flow network to include the demand and supply constraints at each node. The transshipment problem has the following properties:  

Nodes: s, a, b, c, t  
Edges with capacities remain the same.  
Demands (supply or consumption) at each node:  

s: -5 (supply)  
a: 0  
b: 0  
c: 0  
t: 5 (demand)  

**Prove that flow conservation implies demand satisfaction:**   

Flow conservation means that for each node in the network (except for the source and sink), the sum of incoming flows equals the sum of outgoing flows. We have already shown that the maximum flow in the network is 5 units, which equals the demand from s to t. Since the flow conservation is satisfied for all nodes, the flow of 5 units must reach the sink node t, implying that the demand is satisfied.  

**Prove that demand satisfaction implies flow conservation:**    

If the demand at the sink node t is satisfied, this means that a flow of 5 units has reached node t. The flow must pass through the intermediate nodes (a, b, c) while respecting the capacities of the edges. Since the capacities are not exceeded and the demand is satisfied, this implies that the flow conservation is maintained at each node in the network.  

In conclusion, we have found a flow of value 5 with a minimum cut and transformed the problem into a transshipment problem. We have shown that flow conservation leads to demand satisfaction and vice versa.  

As further clarification for the proof that the demand satisfaction implies flow conservation, some mathematical developments will be shown.

Let G = (V, E) be a directed graph representing a transshipment problem, where V is the set of vertices (nodes) and E is the set of edges (arcs). Let x_ij denote the flow on the arc (i, j) ∈ E, and let d_i denote the demand at node i. A positive demand indicates supply, while a negative demand indicates consumption. 

To prove that demand satisfaction implies flow conservation, we must show that for each node i ∈ V (except for the source and sink), the sum of incoming flows equals the sum of outgoing flows, given that the demand is satisfied.

**Lemma:** The flow x satisfies the demand d at each node i if and only if the following equation holds:

$$
\sum_{j:(i,j) \in E} x_{ij} - \sum_{j:(j,i) \in E} x_{ji} = d_i \quad \forall i \in V
$$

**Proof:**

(⇒) Suppose that the flow x satisfies the demand d at each node i. By definition, this means that the net flow into node i equals the demand at that node. Thus, the sum of incoming flows minus the sum of outgoing flows equals the demand:

$$
\sum_{j:(i,j) \in E} x_{ij} - \sum_{j:(j,i) \in E} x_{ji} = d_i \quad \forall i \in V
$$

(⇐) Now, suppose the equation holds:

$$
\sum_{j:(i,j) \in E} x_{ij} - \sum_{j:(j,i) \in E} x_{ji} = d_i \quad \forall i \in V
$$

This implies that for each node i, the net flow into the node (the sum of incoming flows minus the sum of outgoing flows) equals the demand at that node. Thus, the flow x satisfies the demand d at each node i.

Now, let's consider any node i ∈ V (excluding the source and sink). Since the demand is satisfied, we have:

$$
\sum_{j:(i,j) \in E} x_{ij} - \sum_{j:(j,i) \in E} x_{ji} = d_i = 0
$$

Rearranging the terms, we get:

$$
\sum_{j:(i,j) \in E} x_{ij} = \sum_{j:(j,i) \in E} x_{ji}
$$

This equation states that for each node i (except for the source and sink), the sum of incoming flows equals the sum of outgoing flows, which is the definition of flow conservation.

Thus, we have shown that demand satisfaction implies flow conservation.


### HW13: L21 - Verify the dual

**Primal problem:**

Minimize:

$$
W = \sum_{i,j} c_{ij} \cdot x_{ij}
$$

Subject to:

$$
\sum_{j} x_{ij} \geq 1 \quad \forall i \quad (\text{corresponding to } \alpha_i \text{ variables in primal}) \\
\sum_{i} x_{ij} \geq 1 \quad \forall j \quad (\text{corresponding to } \beta_j \text{ variables in primal}) \\
x_{ij} \geq 0 \quad \forall i, j
$$


**Dual problem:**

Maximize:

$$
Z = \sum_{i} \alpha_i + \sum_{j} \beta_j
$$

Subject to:

$$
\alpha_i + \beta_j \leq c_{ij} \quad \forall i, j \\
\alpha_i \geq 0 \quad \forall i \\
\beta_j \geq 0 \quad \forall j
$$


To verify the weak duality theorem for the given primal and dual linear programs, we need to show that the objective value of the primal is always greater than or equal to the objective value of the dual.

For the given primal and dual problems, consider any feasible solution for both the primal and the dual problems.

**Primal objective value:**

$$
W = \sum_{i,j} c_{ij} \cdot x_{ij}
$$

**Dual objective value:**

$$
Z = \sum_{i} \alpha_i + \sum_{j} \beta_j
$$

Since the primal constraints are:

$$
\sum_{j} x_{ij} \geq 1 \quad \forall i \\
\sum_{i} x_{ij} \geq 1 \quad \forall j \\
x_{ij} \geq 0 \quad \forall i, j
$$

And the dual constraints are:

$$
\alpha_i + \beta_j \leq c_{ij} \quad \forall i, j \\
\alpha_i \geq 0 \quad \forall i \\
\beta_j \geq 0 \quad \forall j
$$

We have:

$$
\sum_{i} \alpha_i + \sum_{j} \beta_j = Z \leq \sum(\alpha_i + \beta_j) \leq \sum_{i,j} c_{ij} \cdot x_{ij} = W
$$

Thus, we have shown that Z <= W, verifying the weak duality theorem for the given primal and dual linear programs.


### HW14: L22

Homework 13 and 14 are the same 

Just in case, I will finish the last proof of the L22

**Show the complexity and correctness proof of the Hungarian method**

The Hungarian method, also known as the Kuhn-Munkres algorithm or Munkres assignment algorithm, is a combinatorial optimization algorithm that solves the assignment problem in polynomial time. The assignment problem is a special case of the linear sum assignment problem, where the goal is to find the minimum-weight perfect matching in a weighted bipartite graph.

**Complexity:**

The Hungarian algorithm has a worst-case time complexity of O(n^3), where n is the number of vertices on each side of the bipartite graph. This complexity is achieved by first transforming the original cost matrix into a matrix that has a zero in every row and column (which takes O(n^2) time) and then repeatedly searching for augmenting paths and updating the labels (which takes O(n^3) time).

**Correctness proof:**

The Hungarian algorithm is based on the concepts of feasible vertex labeling and equality subgraph. The algorithm maintains the invariant that the current labeling is feasible, and the equality subgraph has a perfect matching if and only if the labeling is optimal. The proof of correctness can be broken down into the following steps:

- Initialization: The algorithm starts with an initial feasible labeling (e.g., by subtracting the minimum value in each row and then in each column). It is easy to see that the initial labeling is feasible because it satisfies the constraints of the primal problem.

- Maintaining feasibility: During the execution of the algorithm, the labels are updated by changing the dual variables in a manner that maintains the feasibility of the labeling. This is done by selecting a set of rows and columns and updating the labels according to the rules of the algorithm.

- Optimality: The algorithm terminates when a perfect matching is found in the equality subgraph of the current labeling. At this point, the algorithm has found an optimal solution because the current labeling is both feasible and has a perfect matching in the equality subgraph. By the complementary slackness theorem, an optimal solution to the dual problem can be found by setting x_{ij} = 1 if the corresponding edge is in the perfect matching and x_{ij} = 0 otherwise. Since the primal and dual problems have the same objective value at optimality, the algorithm has found an optimal solution to the assignment problem.

- Termination: The algorithm terminates in polynomial time because each iteration either improves the current solution or increases the size of the partial matching. Since there are at most n iterations, the total number of iterations is bounded by O(n^3).

In summary, the Hungarian method is a polynomial-time algorithm for solving the assignment problem, and its correctness can be proved using the concepts of feasible labeling, equality subgraph, and complementary slackness.